baseURL = "https://nagarajrpoojari.github.io/opennotes"
languageCode = "en-us"
title = "opennotes"
theme = "skyfall"

[permalinks]
  posts = "/:year/:slug/"

[markup.goldmark.renderer]
  unsafe = true

[params]
  githubUsername = "nagarajRPoojari"
  goatSiteName = "nagarajrpoojari"
  rcscout = "a4aabd5087bb19daf083302de1b46650"
  customCSS = ["css/custom.css"]

[menu]
  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects"
